language: node_js
node_js:
    - 13

services:
    - docker

# Pre-testing installs
install:
    - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
    - echo "no tests"

script:
    - docker --version # print the version for logging
    - docker build -t travis-env-vars --build-arg FAVORITE_GAME=${FAVORITE_GAME} .
    - docker tag travis-env-vars floturner/travis-env-vars:latest

after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push floturner/travis-env-vars
